apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-petclinic
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hongphuchcmus/springboot-petclinic-gitops.git
    targetRevision: HEAD
    path: config
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true
