nameOverride: admin-server
serviceName: admin-server

replicaCount: 1

image:
  repository: hongphuchcmus/spring-petclinic-admin-server
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 9090
springProfile: docker

service:
  type: NodePort
  port: 9090
  nodePort: 30100

resources: {}